
# python rcl_lstm.py --config configs_lstm.yaml

seed: 71
experiment:
  name: "rcl_VGG_lstm_permuted_mnist"
  out_dir: "./runs/rcl_VGG_lstm_permuted_mnist"

training:
  device: "cuda"              # "cpu" o "cuda"
  batch_size: 512
  epochs_task: 7
  lr_task: 0.001
  lr_controller: 0.001
  lr_value: 0.005
  controller_trials: 20       # number of child net for task
  grad_clip: 5.0

rcl:
  reward_alpha: 0.01        # MNIST permutations  0.0003

dataset:
  _target_: dataset:PermutedMNISTDataset
  data_dir: "./data"
  num_tasks: 10
  permutation_seed: 1900
  train_val_split: 0.9
  num_workers: 0 #1


task_net:
  _target_: task_nets.expandable_vgg:ExpandableVGG
  in_channels: 1
  block_specs: [[1, 32], [1, 64], [2, 128], [2, 256]]    #[128, 240, 296, 408]
  num_classes: 10
  action_spec: [11, 11, 11, 11]
  delta_step: 8
  use_gap: true
  dropout: 0.1

controller:
  _target_: controllers.lstm_controller:LSTMController
  hidden_size: 100
  num_layers: 2

value_net:
  _target_: value_nets.mlp_value:MLPValueNet
  hiddensize: 100

evaluation:
  batch_size: 256
  device: "cuda"







